[build]
  # Build command for the frontend
  command = "npm run build"
  
  # Directory to publish (where build output goes)
  publish = "dist/public"
  
  # Set Node.js version
  [build.environment]
    NODE_VERSION = "20"
    NODE_ENV = "production"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes - redirect to external backend (you'll need to update the URL)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-deployment.herokuapp.com/api/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard)
# VITE_API_URL = "https://your-backend-deployment.herokuapp.com"
# MONGODB_URI = "your-mongodb-connection-string"